In [1]:
import numpy as np
import pandas as pd

In [2]:
walk = pd.read_csv('data/EPA_Walkability.csv')
air = pd.read_csv('data/annual_aqi_by_county_2019.csv')

In [3]:
walk

,OBJECTID,GEOID10,GEOID20,STATEFP,COUNTYFP,TRACTCE,BLKGRPCE,CSA,CSA_Name,CBSA,...,D5DRI,D5DE,D5DEI,D2A_Ranked,D2B_Ranked,D3B_Ranked,D4A_Ranked,NatWalkInd,Shape_Length,Shape_Area
0,1,4.811300e+11,4.811300e+11,48,113,7825,4,206.0,"Dallas-Fort Worth, TX-OK",19100.0,...,0.184697,0.000476,0.137707,6,14,15,17,14.000000,3110.360820,2.978361e+05
1,2,4.811300e+11,4.811300e+11,48,113,7825,2,206.0,"Dallas-Fort Worth, TX-OK",19100.0,...,0.323221,0.000801,0.231868,3,10,12,14,10.833333,3519.469110,4.849451e+05
2,3,4.811300e+11,4.811300e+11,48,113,7825,3,206.0,"Dallas-Fort Worth, TX-OK",19100.0,...,0.314628,0.000736,0.213146,1,1,7,17,8.333333,1697.091802,1.067059e+05
3,4,4.811300e+11,4.811300e+11,48,113,7824,1,206.0,"Dallas-Fort Worth, TX-OK",19100.0,...,0.229821,0.000708,0.205018,16,10,17,17,15.666667,2922.609204,4.818284e+05
4,5,4.811300e+11,4.811300e+11,48,113,7824,2,206.0,"Dallas-Fort Worth, TX-OK",19100.0,...,0.164863,0.000433,0.125296,4,7,11,14,10.166667,3731.971773,6.876848e+05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
220735,220736,7.803100e+11,7.803100e+11,78,30,961000,2,NaN,NaN,NaN,...,-99999.000000,-99999.000000,-99999.000000,1,1,20,1,7.333333,3414.446949,3.355857e+05
220736,220737,7.803100e+11,7.803100e+11,78,30,961000,3,NaN,NaN,NaN,...,-99999.000000,-99999.000000,-99999.000000,1,1,20,1,7.333333,2421.025608,2.924305e+05
220737,220738,7.803100e+11,7.803100e+11,78,30,961000,5,NaN,NaN,NaN,...,-99999.000000,-99999.000000,-99999.000000,1,1,20,1,7.333333,1955.909418,1.619395e+05
220738,220739,7.803100e+11,7.803100e+11,78,30,960700,3,NaN,NaN,NaN,...,-99999.000000,-99999.000000,-99999.000000,1,1,10,1,4.000000,16896.768870,1.038966e+07
220739,220740,7.803100e+11,7.803100e+11,78,30,960200,2,NaN,NaN,NaN,...,-99999.000000,-99999.000000,-99999.000000,1,1,12,1,4.666667,3890.488237,6.114601e+05

In [4]:
air

,State,County,Year,Days with AQI,Good Days,Moderate Days,Unhealthy for Sensitive Groups Days,Unhealthy Days,Very Unhealthy Days,Hazardous Days,Max AQI,90th Percentile AQI,Median AQI,Days CO,Days NO2,Days Ozone,Days PM2.5,Days PM10
0,Alabama,Baldwin,2019,271,237,34,0,0,0,0,80,52,37,0,0,220,51,0
1,Alabama,Clay,2019,107,97,10,0,0,0,0,67,50,30,0,0,0,107,0
2,Alabama,Colbert,2019,263,252,11,0,0,0,0,61,47,37,0,0,228,35,0
3,Alabama,DeKalb,2019,361,324,37,0,0,0,0,90,51,39,0,0,331,30,0
4,Alabama,Elmore,2019,228,208,20,0,0,0,0,100,50,39,0,0,228,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015,Wyoming,Sublette,2019,365,266,88,8,3,0,0,200,71,46,0,0,363,2,0
1016,Wyoming,Sweetwater,2019,365,262,100,3,0,0,0,133,64,46,0,4,321,5,35
1017,Wyoming,Teton,2019,365,326,39,0,0,0,0,87,51,43,0,0,359,4,2
1018,Wyoming,Uinta,2019,365,315,49,1,0,0,0,101,58,44,0,1,360,0,4
1019,Wyoming,Weston,2019,360,335,25,0,0,0,0,71,49,40,0,0,360,0,0

In [5]:
#removing missing data 
walk = walk.replace(-99999.00, np.nan)
walk = walk.replace(-99999, np.nan)
walk.isna().sum()

OBJECTID        0
GEOID10         1
GEOID20         0
STATEFP         0
COUNTYFP        0
               ..
D3B_Ranked      0
D4A_Ranked      0
NatWalkInd      0
Shape_Length    0
Shape_Area      0
Length: 117, dtype: int64

In [6]:
walk[['STATEFP','COUNTYFP']] = walk[['STATEFP','COUNTYFP']].astype(str)
walk.loc[:, 'STATEFP'] = walk['STATEFP'].apply(lambda x: str(x).zfill(2))
walk.loc[:, 'COUNTYFP'] = walk['COUNTYFP'].apply(lambda x: str(x).zfill(3))
walk['COUNTY_FIPS'] = walk['STATEFP'] + walk['COUNTYFP']

In [7]:
my_list = []
with open('data/fips.txt', 'r') as file:
    for line in file:
        # Process each line as needed
        counties = line.strip().split(maxsplit = 1)
        my_list.append(counties)

In [8]:
# Create a mapping dictionary
mapping_dict = dict(my_list)

# Use map to convert COUNTY FIPS to COUNTY NAME
walk['COUNTY'] = walk['COUNTY_FIPS'].map(mapping_dict).fillna(walk['COUNTY_FIPS'])

In [9]:
walk.dropna(subset = ['CBSA'])

,OBJECTID,GEOID10,GEOID20,STATEFP,COUNTYFP,TRACTCE,BLKGRPCE,CSA,CSA_Name,CBSA,...,D5DEI,D2A_Ranked,D2B_Ranked,D3B_Ranked,D4A_Ranked,NatWalkInd,Shape_Length,Shape_Area,COUNTY_FIPS,COUNTY
0,1,4.811300e+11,4.811300e+11,48,113,7825,4,206.0,"Dallas-Fort Worth, TX-OK",19100.0,...,0.137707,6,14,15,17,14.000000,3110.360820,297836.0831,48113,Dallas County
1,2,4.811300e+11,4.811300e+11,48,113,7825,2,206.0,"Dallas-Fort Worth, TX-OK",19100.0,...,0.231868,3,10,12,14,10.833333,3519.469110,484945.1466,48113,Dallas County
2,3,4.811300e+11,4.811300e+11,48,113,7825,3,206.0,"Dallas-Fort Worth, TX-OK",19100.0,...,0.213146,1,1,7,17,8.333333,1697.091802,106705.9281,48113,Dallas County
3,4,4.811300e+11,4.811300e+11,48,113,7824,1,206.0,"Dallas-Fort Worth, TX-OK",19100.0,...,0.205018,16,10,17,17,15.666667,2922.609204,481828.4303,48113,Dallas County
4,5,4.811300e+11,4.811300e+11,48,113,7824,2,206.0,"Dallas-Fort Worth, TX-OK",19100.0,...,0.125296,4,7,11,14,10.166667,3731.971773,687684.7752,48113,Dallas County
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
220646,220647,7.202100e+11,7.202100e+11,72,021,30200,2,490.0,"San Juan-Bayamón, PR",41980.0,...,NaN,1,1,18,1,6.666667,1632.404551,139386.4852,72021,72021
220647,220648,7.202100e+11,7.202100e+11,72,021,31401,2,490.0,"San Juan-Bayamón, PR",41980.0,...,NaN,1,1,17,1,6.333333,1474.513645,109441.0787,72021,72021
220648,220649,7.202100e+11,7.202100e+11,72,021,31202,1,490.0,"San Juan-Bayamón, PR",41980.0,...,NaN,1,1,16,1,6.000000,2112.392508,199405.4456,72021,72021
220649,220650,7.205320e+11,7.205320e+11,72,053,150400,3,490.0,"San Juan-Bayamón, PR",41980.0,...,NaN,1,1,14,1,5.333333,4448.103039,498971.9856,72053,72053
220650,220651,7.205320e+11,7.205320e+11,72,053,150104,4,490.0,"San Juan-Bayamón, PR",41980.0,...,NaN,1,1,13,1,5.000000,3645.554606,621538.6947,72053,72053

In [10]:
walk.rename(columns = {'CBSA': 'CBSA Code'}, inplace = True)
air['County'] = air['County'] + ' County'
air.rename(columns = {'County':'COUNTY'}, inplace = True)

In [11]:
merged = pd.merge(air, walk, on = 'COUNTY')
merged

,State,COUNTY,Year,Days with AQI,Good Days,Moderate Days,Unhealthy for Sensitive Groups Days,Unhealthy Days,Very Unhealthy Days,Hazardous Days,...,D5DE,D5DEI,D2A_Ranked,D2B_Ranked,D3B_Ranked,D4A_Ranked,NatWalkInd,Shape_Length,Shape_Area,COUNTY_FIPS
0,Alabama,Baldwin County,2019,271,237,34,0,0,0,0,...,NaN,NaN,20,20,6,1,9.000000,18243.810720,1.709580e+07,01003
1,Alabama,Baldwin County,2019,271,237,34,0,0,0,0,...,NaN,NaN,14,6,9,1,6.666667,7001.465703,2.725634e+06,01003
2,Alabama,Baldwin County,2019,271,237,34,0,0,0,0,...,NaN,NaN,14,4,2,1,4.000000,63329.587750,1.405586e+08,01003
3,Alabama,Baldwin County,2019,271,237,34,0,0,0,0,...,NaN,NaN,8,12,4,1,5.000000,45443.041950,7.058860e+07,01003
4,Alabama,Baldwin County,2019,271,237,34,0,0,0,0,...,NaN,NaN,16,20,6,1,8.333333,23543.542730,2.511771e+07,01003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
384320,Wyoming,Weston County,2019,360,335,25,0,0,0,0,...,NaN,NaN,11,15,1,1,5.000000,226756.773000,1.995829e+09,56045
384321,Wyoming,Weston County,2019,360,335,25,0,0,0,0,...,NaN,NaN,13,15,1,1,5.333333,419217.773200,4.109223e+09,56045
384322,Wyoming,Weston County,2019,360,335,25,0,0,0,0,...,NaN,NaN,12,14,3,1,5.666667,51219.142920,5.989268e+07,56045
384323,Wyoming,Weston County,2019,360,335,25,0,0,0,0,...,NaN,NaN,15,14,4,1,6.500000,28246.773320,4.070376e+07,56045
384324,Wyoming,Weston County,2019,360,335,25,0,0,0,0,...,NaN,NaN,20,20,7,1,9.333333,16445.723940,1.038138e+07,56045

In [12]:
numerical_columns = merged.select_dtypes(include=['int', 'float']).columns

In [13]:
numerical_columns

Index(['Year', 'Days with AQI', 'Good Days', 'Moderate Days',
       'Unhealthy for Sensitive Groups Days', 'Unhealthy Days',
       'Very Unhealthy Days', 'Hazardous Days', 'Max AQI',
       '90th Percentile AQI',
       ...
       'D5DRI', 'D5DE', 'D5DEI', 'D2A_Ranked', 'D2B_Ranked', 'D3B_Ranked',
       'D4A_Ranked', 'NatWalkInd', 'Shape_Length', 'Shape_Area'],
      dtype='object', length=129)

In [14]:
averaged = merged.groupby('COUNTY')[numerical_columns].mean().reset_index()

In [15]:
non_numerical = merged[['COUNTY','State' ]].drop_duplicates()

In [16]:
averaged = pd.merge(averaged, non_numerical, on='COUNTY')

In [17]:
averaged.insert(0, 'State', averaged.pop('State'))

In [18]:
averaged.to_csv("data/merged_data.csv")

In [19]:
averaged

,State,COUNTY,Year,Days with AQI,Good Days,Moderate Days,Unhealthy for Sensitive Groups Days,Unhealthy Days,Very Unhealthy Days,Hazardous Days,...,D5DRI,D5DE,D5DEI,D2A_Ranked,D2B_Ranked,D3B_Ranked,D4A_Ranked,NatWalkInd,Shape_Length,Shape_Area
0,Idaho,Ada County,2019.0,365.000000,317.000000,48.0,0.000000,0.0,0.0,0.0,...,0.500129,0.008968,0.399708,12.165680,14.698225,12.982249,10.236686,12.216963,10288.996959,1.625364e+07
1,Oklahoma,Adair County,2019.0,365.000000,338.000000,27.0,0.000000,0.0,0.0,0.0,...,NaN,NaN,NaN,10.582090,9.567164,6.522388,1.000000,5.865672,38067.289563,8.231462e+07
2,Colorado,Adams County,2019.0,331.600000,279.200000,52.2,0.200000,0.0,0.0,0.0,...,0.198808,0.009215,0.191837,10.430451,10.120301,10.409774,7.193609,9.292920,19527.412742,4.846652e+07
3,Illinois,Adams County,2019.0,331.600000,279.200000,52.2,0.200000,0.0,0.0,0.0,...,0.198808,0.009215,0.191837,10.430451,10.120301,10.409774,7.193609,9.292920,19527.412742,4.846652e+07
4,Ohio,Adams County,2019.0,331.600000,279.200000,52.2,0.200000,0.0,0.0,0.0,...,0.198808,0.009215,0.191837,10.430451,10.120301,10.409774,7.193609,9.292920,19527.412742,4.846652e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
953,California,Yolo County,2019.0,365.000000,284.000000,80.0,1.000000,0.0,0.0,0.0,...,0.039038,0.000450,0.085792,11.311475,11.409836,12.745902,14.680328,12.928962,13133.425225,2.172970e+07
954,Maine,York County,2019.0,320.333333,264.666667,53.0,2.666667,0.0,0.0,0.0,...,0.350988,0.006948,0.391921,11.361156,11.486356,8.711075,4.605136,8.246656,15517.092569,1.524461e+07
955,Pennsylvania,York County,2019.0,320.333333,264.666667,53.0,2.666667,0.0,0.0,0.0,...,0.350988,0.006948,0.391921,11.361156,11.486356,8.711075,4.605136,8.246656,15517.092569,1.524461e+07
956,South Carolina,York County,2019.0,320.333333,264.666667,53.0,2.666667,0.0,0.0,0.0,...,0.350988,0.006948,0.391921,11.361156,11.486356,8.711075,4.605136,8.246656,15517.092569,1.524461e+07
957,Arizona,Yuma County,2019.0,365.000000,265.000000,97.0,3.000000,0.0,0.0,0.0,...,0.346675,0.010753,0.413134,9.357616,7.947020,10.695364,9.927152,9.758278,23589.231598,1.352909e+08